version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_HOST: "${MYSQL_HOST}"
      REDIS_HOST: "${REDIS_HOST}"
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0.26
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    security_opt:
      - seccomp:unconfined
  redis:
    image: redis:buster
    ports:
      - 6379:6379
